### ISSUE TITLE
object 'X' not found

### ISSUE THREAD

**Issue by PietJones** [sumbose/iRF#1]
Hi,

When running the iRF function, I found that the training variable x is referred to in the body of the function as X, this is line 24 and 25 in the iRF.R code. Is this a typo?

P

**Comment by sumbose** [comment]
Thanks for catching this. I have fixed the typo. Let me know if the issue
persists.

--
Sumanta

Thanks and Regards,
Sumanta Basu
Assistant Professor
Shayegani Bruno Family Faculty Fellow
Department of Biological Statistics and Computational Biology
Department of Statistical Science
Cornell University
http://faculty.bscb.cornell.edu/~basu/

**Comment by sumbose** [comment]
Thanks for catching this. I fixed the typo. Let me know if the issue
persists.

--
Sumanta

Thanks and Regards,
Sumanta Basu
Assistant Professor
Shayegani Bruno Family Faculty Fellow
Department of Biological Statistics and Computational Biology
Department of Statistical Science
Cornell University
http://faculty.bscb.cornell.edu/~basu/
